django_proj/blog/urls.py
from django.urls import path
from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('/category/<str:slug>/', views.category_page),
    path('/category/<str:slug>', views.category_page),
    path('/<int:pk>',views.PostDetail.as_view()),
    path('/<int:pk>/',views.PostDetail.as_view()),
    #path('',views.index),
    path('',views.PostList.as_view())
]

django_proj/do_it_django/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('blog',include('blog.urls')),
    path('blog/',include('blog.urls')),
    path('admin/', admin.site.urls),
    path('',include('single_pages.urls')),
    
]
urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

django_proj/single_pages/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('about_me/',views.about_me),
    path('about_me',views.about_me),
    path('', views.landing)
]

django_proj/blog/models.py
from enum import auto
from django.db import models
import os
from django.contrib.auth.models import User

# Create your models here.

class Category(models.Model):
    
    name = models.CharField(max_length=50,unique=True)
    slug = models.SlugField(max_length=200,unique=True,allow_unicode=True)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return f'/blog/category/{self.slug}'

    class Meta:
        verbose_name_plural = 'Categories'

class Post(models.Model):
    title = models.CharField(max_length=30)
    hook_text = models.CharField(max_length=100,blank=True)
    content = models.TextField()

    head_image = models.ImageField(upload_to='blog/images/%Y/%m/%d', blank=True)
    file_upload = models.FileField(upload_to='blog/files/%Y/%m/%d', blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    author = models.ForeignKey(User,null=True,on_delete=models.SET_NULL)

    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self) -> str:
        return f'[{self.pk}]{self.title} :: {self.author}'

    def get_absolute_url(self):
        return f'/blog/{self.pk}'

    def get_file_name(self):
        return os.path.basename(self.file_upload.name)

    def get_file_ext(self):
        return self.get_name().split('.')[-1]

django_proj/single_pages/models.py
from django.db import models

# Create your models here.

django_proj/blog/views.py
from django.shortcuts import render
from django.views.generic import ListView,DetailView
from .models import Post, Category

# Create your views here.

class PostList(ListView):
    model = Post
    ordering= '-pk'

    def get_context_data(self, **kwargs):
        context=super(PostList,self).get_context_data()
        context['categories']=Category.objects.all()
        context['no_category_post_count']=Post.objects.filter(category=None).count()
        return context


class PostDetail(DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        context=super(PostDetail,self).get_context_data()
        context['categories']=Category.objects.all()
        context['no_category_post_count']=Post.objects.filter(category=None).count()
        return context

def single_post_page(request,pk):
    post = Post.objects.get(pk=pk)

    return render(
        request,
        'blog/single_post_page.html',
        {
            'post':post,
        }
    )
def category_page(request,slug):
    if slug == 'no_category':
        category='미분류'
        post_list=Post.objects.filter(category=None)
    else:
        category = Category.objects.get(slug=slug)
        post_list=Post.objects.filter(category=category),
    return render(
        request,
        'blog/post_list.html',
        {
            'post_list': post_list,
            'categories':Category.objects.all(),
            'no_category_post_count' : Post.objects.filter(category=None).count(),
            'category':category,
        }
    )

django_proj/single_pages/views.py
from django.shortcuts import render

# Create your views here.
def landing(request):
    return render(
        request,
        'single_pages/landing.html'
    )


def about_me(request):
    return render(
        request,
        'single_pages/about_me.html'
    )

django_proj/blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>{% block head_title %}Blog{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'blog/bootstrap/bootstrap.min.css' %}" media="screen">
        <script src="https://kit.fontawesome.com/767cc826b6.js" crossorigin="anonymous"></script>
    </head>
    <body>
        {% include 'blog/navbar.html' %}
            <div class="container my-3">
                <div class ="row">
                    <div class = "col-md-8 col-lg-9" id="main-area">
                      {% block main_area %}
                      {% endblock %}



                    </div>
                    
                </div>
                    <nav aria-label="Pagination">
                        <hr class="my-0" />
                        <ul class="pagination justify-content-center my-4">
                            <li class="page-item disabled"><a class="page-link" href="#" tabindex="-1" aria-disabled="true">Newer</a></li>
                            <li class="page-item active" aria-current="page"><a class="page-link" href="#!">1</a></li>
                            <li class="page-item"><a class="page-link" href="#!">2</a></li>
                            <li class="page-item"><a class="page-link" href="#!">3</a></li>
                            <li class="page-item disabled"><a class="page-link" href="#!">...</a></li>
                            <li class="page-item"><a class="page-link" href="#!">15</a></li>
                            <li class="page-item"><a class="page-link" href="#!">Older</a></li>
                        </ul>
                    </nav> 
                </div>
                <div class="col-md-4 col-lg-3">
                    <div class="card mb-4">
                        <div class="card-header">Search</div>
                            <div class="card-body">
                                <div class="input-group">
                                    <input class="form-control" type="text" placeholder="Enter search term..." aria-label="Enter search term..." aria-describedby="button-search" />
                                    <button class="btn btn-primary" id="button-search" type="button">Go!</button>
                                </div>
                            </div>
                        </div>
                    <div class="card mb-4" id="categories-card">
                        <div class="card-header">Categories</div>
                            <div class="card-body">
                                <div class="row">
                            
                                    <ul>
                                        {% for category in categories %}
                                        <li>
                                            <a href="{{ category.get_absolute_url}}">{{ category }} ({{category.post_set.count}})</a>
                                        </li>
                                        {%endfor%}
                                        <li>
                                            <a href='/blog/category/no_category/'>미분류 ({{ no_category_post_count }})</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
          {% include 'blog/footer.html' %}
          <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
                integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
                crossorigin="anonymous">
            </script>
          <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
                integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
                crossorigin="anonymous">
            </script>
          <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js"
                integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF"
                crossorigin="anonymous">
            </script>

        
    </body>
</html>

django_proj/blog/templates/blog/footer.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>{% block head_title %}Blog{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'blog/bootstrap/bootstrap.min.css' %}" media="screen">
        <script src="https://kit.fontawesome.com/767cc826b6.js" crossorigin="anonymous"></script>
    </head>
    <body>
      <footer class="py-5 bg-dark">
        <div class="container">
          <p class="m-0 text-center text-white">
            Copyright &copy; Do It Django A to Z 2021
          </p>
        </div>
      </footer>
          
    </body>
</html>

django_proj/blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="UTF-8">
        <title>Blog</title>
    </head>
    <body>
        <h1>Blog</h1>

    {% for p in posts %}
        <hr/>
        <h2><a href="{{ p.get_absolute_url }}">{{ p.title }}</a></h2>
        <h4>{{p.created_at}}</h4>
        <p>{{p.content}}</p>
    {% endfor %}
    </body>
</html>

django_proj/blog/templates/blog/navbar.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>{% block head_title %}Blog{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'blog/bootstrap/bootstrap.min.css' %}" media="screen">
        <script src="https://kit.fontawesome.com/767cc826b6.js" crossorigin="anonymous"></script>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
              <a class="navbar-brand" href="/">Do It Django</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="/blog/">Blog</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="/about_me/">About me</a>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Dropdown link
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                      <li><a class="dropdown-item" href="#">Action</a></li>
                      <li><a class="dropdown-item" href="#">Another action</a></li>
                      <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                  </li>
                  
                </ul>
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="#" data-toggle="modal" data-target="#loginModal"><i class="fas fa-sign-in-alt"></i>&nbsp Log In</a>
                    </li>
                </ul>
                    
              </div>
            </div>
          </nav>
          <!-- Modal -->
          <div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="loginModalLabel" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="loginModalLabel"><i class="fas fa-sign-in-alt"></i> Log-in</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                  <div class="row">
                    <div class="col-md-6">
                      <button type="button" class="btn btn-outline-dark w-100 btn-sm"><i class="fab fa-google"></i> Log in with google</button>
                      <button type="button" class="btn btn-outline-dark w-100 btn-sm"><i class="far fa-envelope"></i> Log in with E-mail</button>
                    </div>
                    <div class="col-md-6">
                      <button type="button" class="btn btn-outline-dark w-100 btn-sm"><i class="far fa-envelope"></i> Sign up with E-mail</button>
                    </div>
                    
                  </div>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                  <button type="button" class="btn btn-primary">Save changes</button>
                </div>
              </div>
            </div>
          </div>
          
    </body>
</html>

django_proj/blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block head_title %}
    {{post.title}} - Blog
{% endblock %}
{% block main_area %}
                    <div id="post-area">
                        {% if post.category %}
                          <span class="badge badge-secondary float-right">{{post.category}}</span>
                        {% else %}
                        <span class="badge badge-secondary float-right">미분류</span>
                        {% endif %}
                        <h1 class="fw-bolder mb-1">{{post.title}}</h1>
                        
                        <h5 class="text-muted">{{post.hook_text}}</h5>
                        
                        <p class="lead">
                            by
                            <a href="#">{{ post.author | upper }}</a>
                        </p>
                        <hr>
                        <!-- Date/Time-->
                        <p>{{post.created_at}}</p>
                        <hr>
                        
                        <!-- Post categories-->
                        <a class="badge bg-secondary text-decoration-none link-light" href="#!">Web Design</a>
                        <a class="badge bg-secondary text-decoration-none link-light" href="#!">Freebies</a>
                    
                        <!-- Preview image figure-->
                        <figure class="mb-4"><img class="img-fluid rounded" src="https://dummyimage.com/900x400/ced4da/6c757d.jpg" alt="..." /></figure>
                        <!-- Post content-->
                        <p>{{ post.content}}</p>

                        {% if post.file_upload %}
                            <a href="{{post.file_upload.url}}" class="btn btn-outline-dark" role="button" >Download:
                            {% if post.get_file_ext == 'pdf' %}
                            <i class="fas fa-file-csv"></i>
                            {% else %}
                            <i class="far fa-file"></i>
                            {% endif %}
                        {{post.get_file_name}}
                        {% endif %}
                        </a>
                    </div>
                {% endblock %}
                    
                    
            <div id="comment-area">
                <!-- Comments section-->
                <section class="mb-5">
                    <div class="card bg-light">
                        <div class="card-body">
                            <!-- Comment form-->
                            <form class="mb-4"><textarea class="form-control" rows="3" placeholder="Join the discussion and leave a comment!"></textarea></form>
                            <!-- Comment with nested comments-->
                            <div class="d-flex mb-4">
                                <!-- Parent comment-->
                                <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                                <div class="ms-3">
                                    <div class="fw-bold">Commenter Name</div>
                                    If you're going to lead a space frontier, it has to be government; it'll never be private enterprise. Because the space frontier is dangerous, and it's expensive, and it has unquantified risks.
                                    <!-- Child comment 1-->
                                    <div class="d-flex mt-4">
                                        <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                                        <div class="ms-3">
                                            <div class="fw-bold">Commenter Name</div>
                                            And under those conditions, you cannot establish a capital-market evaluation of that enterprise. You can't get investors.
                                        </div>
                                    </div>
                                    <!-- Child comment 2-->
                                    <div class="d-flex mt-4">
                                        <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                                        <div class="ms-3">
                                            <div class="fw-bold">Commenter Name</div>
                                            When you put money directly to a problem, it makes a good headline.
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- Single comment-->
                            <div class="d-flex">
                                <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                                <div class="ms-3">
                                    <div class="fw-bold">Commenter Name</div>
                                    When I look at the universe and all the ways the universe wants to kill us, I find it hard to reconcile that with statements of beneficence.
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
            <!-- Side widgets-->
            <div class="col-lg-4">
                <!-- Search widget-->
                <div class="card mb-4">
                    <div class="card-header">Search</div>
                    <div class="card-body">
                        <div class="input-group">
                            <input class="form-control" type="text" placeholder="Enter search term..." aria-label="Enter search term..." aria-describedby="button-search" />
                            <button class="btn btn-primary" id="button-search" type="button">Go!</button>
                        </div>
                    </div>
                </div>
                <!-- Categories widget-->
                <div class="card mb-4">
                    <div class="card-header">Categories</div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-6">
                                <ul class="list-unstyled mb-0">
                                    <li><a href="#!">Web Design</a></li>
                                    <li><a href="#!">HTML</a></li>
                                    <li><a href="#!">Freebies</a></li>
                                </ul>
                            </div>
                            <div class="col-sm-6">
                                <ul class="list-unstyled mb-0">
                                    <li><a href="#!">JavaScript</a></li>
                                    <li><a href="#!">CSS</a></li>
                                    <li><a href="#!">Tutorials</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Side widget-->
                <div class="card mb-4">
                    <div class="card-header">Side Widget</div>
                    <div class="card-body">You can put anything you want inside of these side widgets. They are easy to use, and feature the Bootstrap 5 card component!</div>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer-->
    <footer class="py-5 bg-dark">
        <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2021</p></div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="js/scripts.js"></script>
</body>
</html>

django_proj/blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}
{% block main_area %}

<h1>Blog {% if category %}<span class="badge bg-secondary">{{ category }}</span>{% endif %}</h1>
                    {% if post_list.exists %}
                    {% for p in post_list %}
                    <!-- Blog post-->
                    <div class="card mb-4" id="post-{{p.pk}}">
                      {% if p.head_image %}
                      <img class="card-img-top" src="{{p.head_image.url}}" alt="{{p}} head image" /></a>
                      
                      {% else %}
                      <img class="img-fluid rounded" src="https://picsum.photos/seed/{{p.id}}/800/200" alt="random_image">
                      
                      {% endif %}
                      <div class="card-body">
                        {% if p.category %}
                          <span class="badge bg-secondary float-right">{{p.category}}</span>
                        {% else %}
                        <span class="badge bg-secondary float-right">미분류</span>
                        {% endif %}
                          <div class="small text-muted">January 1, 2021</div>
                          <h2 class="card-title h4">{{p.title}}</h2>
                          {% if p.hook_text %}
                            <h5 class="text-muted">{{p.hook_text}}</h5>
                          {% endif %}
                          <p class="card-text">{{p.content | truncatewords:15}}</p>
                          <a class="btn btn-primary" href="{{p.get_absolute_url}}">Read more →</a>
                      </div>

                      <div class="card-footer text-muted">
                          Posted on {{p.created_at}} by
                          <a href="#">{{ p.author | upper }}</a>
                      </div>
                      {%endfor%}
                    {% else %}
                      <h3>아직 게시물이 없습니다</h3>
                    {% endif %}
                  </div>


{% endblock %}

django_proj/single_pages/templates/single_pages/about_me.html
<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="UTF-8">
        <title>개발자 한샹곰</title>
    </head>

    <body>
        <nav>
            <a href="/blog/">Blog</a>
            <a href="/about_me/">About me</a>
        </nav>

        <h1>안녕하세요, 한샹곰입니다.</h1>
        <h2>이력</h2>
        <h2>Portfolio</h2>
        <h3>아직 만들지 않음</h3>
    </body>
</html>

django_proj/single_pages/templates/single_pages/landing.html
<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="UTF-8">
        <title>한샹곰</title>
    </head>

    <body>
        <nav>
            <a href="/blog/">Blog</a>
            <a href="/about_me/">About me</a>
        </nav>

        <h1>안녕하세요, 한샹곰입니다.</h1>
        <h2>대문페이지</h2>
        <h3>아직 만들지 않음</h3>
    </body>
</html>